baseURL: ""
languageCode: "en-us"
title: "Madhav Sharma | Portfolio"
theme: "./.."
relativeURLs: true

#googleanalytics: UA-xxxxxx-x
#disqusShortname:
#Paginate: 3
#markup:
#  goldmark:
#    renderer:
#      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"
  
enableEmoji: true
params:
  version: 3
  customCSS: false

  #favicon: https://cdn2.iconfinder.com/data/icons/inclusiveness-vivid-vol-2/256/Scientist-male-512.png 
  description: "Madhav's personal portfolio"

  # Navbar Menus
  

  # home
  disable_home: false
  #profile_image: /images/nav-img.png
  name: "Madhav Sharma"
  namecolor: 17a2b8
  profession: "Aspiring Data Scientist"
  github: "https://github.com/ms21949/"
  linkedin: "https://www.linkedin.com/in/madhavsharma15/"
  #twitter: "https://twitter.com/Rohan20075428"
  gmail: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=madhavsharma511@gmail.com"
  #instagram: "https://instagram.com/__rohan__95?utm_medium=copy_link"
  

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=madhavsharma511@gmail.com"
      fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=madhavsharma511@gmail.com"

  # About
  disable_about: false  
  descripe_l1_person: "An MSc Data Science graduate from the University of Essex, with the ability to highly analyse and implement Predictive Machine Learning models for Forecasting and Classification problems. Skilled in Machine Learning and Natural Language Processing methodologies with Data Manipulation and Visualisation skills using Python and R programming."
  descripe_l2_person: "### KEY ACHIEVEMENTS"
  descripe_l3_person: "Assigned as a team leader for group projects and presentations at the University."
  descripe_l4_person: "Awarded an Academic Excellence International Masters scholarship of  £5000 at the University of Essex."
  descripe_l5_person: "Achieved outstanding results in Statistics and Predictive Modelling using Machine Learning at the University."
  descripe_l6_person: "Earned intern of the month title because of my ability to analyse data, generate successful insights and find appropriate key performance indicators (KPIs)."
  descripe_l7_person: "Awarded as the best final year project during Bachelors for developing an E-Commerce Mobile application by implementing a Cart Discarding analysis and Recommendation System for listed products."
  descripe_l8_person: "Successfully implemented a Machine Learning model for detecting fake reviews and achieved an overall accuracy of 90%."

  skills:
    - name: Microsoft Excel
      percentage: 85
    - name: SQL
      percentage: 80
    - name: Python Programming
      percentage: 80
    - name: R programming
      percentage: 50
    - name: Microsoft PowerBI
      percentage: 50
    - name: Data preprocessing & visualisation
      percentage: 80
    - name: Machine Learning
      percentage: 80
    - name: Natural Language Processing
      percentage: 70
    - name: Predictive Modelling and Forecasting
      percentage: 75
    - name: Amazon Web Services (EC2, S3, Sagemaker)
      percentage: 55
    - name: Git
      percentage: 70
    

  # Experience
  disable_experience: false
  experience:
    - company: "Neubrain-Solutions Pvt. Ltd."
      id: "Neubrain"
      role: "Data Scientist Intern (Mumbai, India)"
      startdate: "October 31 2020"
      enddate: "July 07 2021"
      featuredpoints:
        - point: "Worked on projects such as in-vehicle coupon recommendation systems and fake product review detection for decision making."
        - point: "Manipulated and pre-processed data by using Natural Language Processing libraries and encoders in python."
        - point: "Analysed data to generate intelligent insights by performing Exploratory Data Analysis."
        - point: "Implemented Machine Learning algorithms from the sklearn library in python and performed binary classification and improved the accuracy of the model by performing Hyperparameter Tuning."
    - company: "The Delivery Group"
      id: "TDG"
      role: "Data Processor (Bristol, England)"
      startdate: "May 2023"
      enddate: "-"
      featuredpoints:
        - point: "Receive data files from clients."
        - point: "Check the data files for validity and accuracy."
        - point: "Format the data files for importing into industry-standard software."
        - point: "Data Preparation and Formatting:"
        - point: "Use Excel functions (e.g., LookUp, If functions, Match, Index) to optimise the format and layout of data files."
        - point: "Ensure compliance with Royal Mail (RM) and client requirements."
        - point: "Data Cleansing:"
        - point: "Manipulate client databases and data files to ensure data quality."
        - point: "Conduct quality control checks to identify and rectify potential data problems."
        - point: "Ensure all records are fully and accurately addressed and postcoded according to Royal Mail's Postcode Address File (PAF)."
        - point: "Suppress customer and prospect data against the Mailing Preference Service (MPS), including MPS Deceased."
        - point: "Run data against the client's internal suppression file to remove unwanted entries."
        - point: "Implement data deduplication processes to eliminate duplicate records."
        - point: "Provide reports to customers regarding the results of data cleansing efforts."
        - point: "Data Output and Generation:"
        - point: "Prepare data files for production."
        - point: "Generate output files for mailing or postage purposes."
        - point: "Postage Statements and Labels:"
        - point: "Create postage statements, manifests, and labels hard-copy and electronic versions."
        - point: "Distribute these documents as required."
        - point: "Provide reports to customers regarding the postage and mailing process."
        - point: "Quality Assurance:"
        - point: "Perform a final quality check to compare job specifications with the final product."
        - point: "Ensure compliance with Royal Mail regulations."
        - point: "Liaison with the Sales Team:"
        - point: "Collaborate with the Sales team to address data audit inquiries."
        - point: "Data Handling Compliance:"
        - point: "Ensure that all data handling processes are compliant with the General Data Protection Regulation (GDPR) and other relevant data privacy laws."

    
  #certifications section
  disable_certification: true
  #certification:
  #  - Name: ML-DL-Masters-Course
  #    institution: iNeuron.ai
  #    startdate: "August 2021"
  #    enddate: "August 2022"
  #    link:
  #      - weblink: "https://github.com/rohanpatankar926"
  #        certificate: "View Certificate"
    
  # Education
  disable_education: false
  education:
    - degree: "MSc"
      branch: "Data Science"
      university: "University of Essex"
      startedyear: "2021"
      graduation: "2022"
    - degree: "B.E"
      branch: "Computer Science"
      university: "University of Mumbai"
      startedyear: "2016"
      graduation: "2020"
    - degree: "Diploma"
      branch: "Computer Science"
      university: "Maharashtra State Board of Technical Education (Mumbai)"
      startedyear: "2013"
      graduation: "2016"

  # Projects
  disable_projects: false
  projects:
    - name: "Fake Review Detection Using Supervised Machine Learning"
      img: /images/nlp.png
      githublink: "https://github.com/ms21949/NLP"
      #featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "The idea behind this project was to use WordLemmatizer along with an N-gram Model. Further vectorising the Product-Review text using a Term Frequency - Inverse Document Frequency (TF-IDF) and then fine-tuning a supervised Machine Learning Model to predict if the review is fake or real."
    - name: "Coupon recommendation for vehicle infotainment systems"
      img: /images/vehicle.jpeg
      githublink: "https://github.com/ms21949/Binary-Classification"
      #featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "The following code is based on the dataset which was collected via a survey on Amazon Mechanical Turk. The survey describes different driving scenarios including the destination, current time, weather, passenger, etc., and then ask the person whether he will accept the coupon if he is the driver."
    - name: "Rossmann Store Sales Prediction"
      img: /images/sale.jpeg
      githublink: "https://github.com/ms21949/Sales-Prediction-"
      #featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "Rossmann operates over 3,000 drug stores in 7 European countries. Currently, Rossmann store managers are tasked with predicting their daily sales for up to six weeks in advance. Store sales are influenced by many factors, including promotions, competition, school and state holidays, seasonality, and locality. With thousands of individual managers predicting sales based on their unique circumstances, the accuracy of results can be quite varied."
    - name: "Construction Management Firm Evaluator (Deployed on AWS EC2)"
      img: /images/invest-real-estate-icon-flat-design-house-building-investment-money-industry-financial-finance-business-residential-61464178.jpeg
      githublink: "https://github.com/ms21949/Construction-Management-Firm-Evaluator"
      featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "After scraping and converting the data into a CSV, performed some Exploratory Data Analysis on the Dataset and implemented a Machine Learning Model to predict if the Firm is worth Investing and vice versa.  I have built an interactive Flask Web Application including two fields I. e, Rank and Revenue using the model developed in the previous step. "
    - name: "Credit Score Estimator"
      img: /images/creditscore.jpeg
      githublink: "https://github.com/ms21949/CreditScore-Estimator"
      featuredlink: "https://credit-score-estimator.herokuapp.com/"
      description: "(Work in Progress (Version 1))Given a persons credit-related information, build a machine learning model that can classify the credit score."

    
    
    
    
  # services
  disable_achievements: true
  achievements:
    - title: "Website Development"
      description: "Design a website for personal use or for business purpose using HTML, CSS, JS and Python."
      img: /images/Website-Design-new.jpg
    - title: Data Analysis
      description: "With the help of tableu or python analyze the data of the business or client needs which help them to solve business problems."
      img: /images/da.jpg
      # url: https://example.com
    - title: Machine Learning & Deep Learning
      description: "Build various types of ML and DL models according to business or client needs in which it helps to solve complex business issues." 
      img: /images/ml.png
    
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you! 
  email: "madhavsharma511@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
