baseURL: "https://madhavsharma-portfolio.netlify.app/"
languageCode: "en-us"
title: "Madhav Sharma | Portfolio"
theme: "./.."
relativeURLs: true

googleanalytics: UA-xxxxxx-x
disqusShortname:
Paginate: 3
markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: "tags"
  category: "categories"
  
enableEmoji: true
params:
  version: 3
  customCSS: false

  #favicon: https://cdn2.iconfinder.com/data/icons/inclusiveness-vivid-vol-2/256/Scientist-male-512.png 
  description: "Madhav's personal portfolio"

  # Navbar Menus
  

  # home
  disable_home: false
  #profile_image: /images/nav-img.png
  name: "Madhav Sharma"
  namecolor: 17a2b8
  profession: "Aspiring Data Scientist"
  github: "https://github.com/ms21949/"
  linkedin: "https://www.linkedin.com/in/madhavsharma15/"
  #twitter: "https://twitter.com/Rohan20075428"
  gmail: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=madhavsharma511@gmail.com"
  #instagram: "https://instagram.com/__rohan__95?utm_medium=copy_link"
  

  # Custom social links
  customSocialLinks:
    - fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=madhavsharma511@gmail.com"
      fontAwesomeIconName: "fa fa-envelope"
      url: "https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=madhavsharma511@gmail.com"

  # About
  disable_about: false  
  descripe_l1_person: "As a data enthusiast, I bring a comprehensive skill set that includes advanced proficiency in Excel, Microsoft SQL Server, and Power BI, enabling me to conduct robust data analysis and visualization. My expertise extends to Python programming for data manipulation, statistical analysis, predictive modelling and forecasting to derive actionable insights from complex datasets. I possess knowledge of cloud platforms like Azure and AWS for efficient data management and exploration. Additionally, I have hands-on experience with end-to-end machine learning projects and version control systems like Git, facilitating the development of accurate predictive models and ensuring code integrity throughout the development process. I am well-versed in AWS services such as EC2, S3, and SageMaker, enabling me to deploy scalable data solutions in the cloud environment. Strong organizational and communication skills coupled with meticulous attention to detail benefit me in managing and successfully delivering projects and effectively conveying insights to stakeholders at all levels of the organization. I’m eager to advance the boundaries of data science for a data-driven future."
  descripe_l2_person: "### KEY ACHIEVEMENTS"
  descripe_l3_person: "Assigned as a team leader for group projects and presentations at the University."
  descripe_l4_person: "Awarded an Academic Excellence International Masters scholarship of  £5000 at the University of Essex."
  descripe_l5_person: "Achieved outstanding results in Statistics and Predictive Modelling using Machine Learning at the University."
  descripe_l6_person: "Earned intern of the month title because of my ability to analyse data, generate successful insights and find appropriate key performance indicators (KPIs)."
  descripe_l7_person: "Awarded as the best final year project during Bachelors for developing an E-Commerce Mobile application by implementing a Cart Discarding analysis and Recommendation System for listed products."
  descripe_l8_person: "Successfully implemented a Machine Learning model for detecting fake reviews and achieved an overall accuracy of 90%."

  skills:
    - name: Advanced Excel
      percentage: 85
    - name: Microsoft SQL Server (SSMS & SSRS)
      percentage: 80
    - name: Python Programming
      percentage: 80
    - name: R programming
      percentage: 50
    - name: Microsoft PowerBI (DAX & M)
      percentage: 80
    - name: Data preprocessing & visualisation
      percentage: 80
    - name: Machine Learning
      percentage: 80
    - name: Data cleansing
      percentage: 90
    - name: Natural Language Processing
      percentage: 50
    - name: Predictive Modelling and Forecasting
      percentage: 75
    - name: Azure Data Studio
      percentage: 30
    - name: Amazon Web Services (EC2, S3, Sagemaker)
      percentage: 30
    - name: Git
      percentage: 60
    

  # Experience
  disable_experience: false
  experience:
    - company: "Neubrain-Solutions Pvt. Ltd."
      id: "Neubrain"
      role: "Data Scientist Intern (Mumbai, India)"
      startdate: "October 31 2020"
      enddate: "July 07 2021"
      featuredpoints:
        - point: "Conducting comprehensive data analysis on extensive datasets utilizing advanced tools such as Python and Excel to discern trends, patterns, and key performance indicators (KPIs)."
        - point: "Employing web scraping techniques to gather data from diverse online sources while adhering to GDPR regulations, followed by proficiently loading the acquired data into various SQL databases. Subsequent tasks involve data transformation and preparation to facilitate future analytical endeavours."
        - point: "Engaging in stakeholder and client communication to effectively identify problem statements, thereby formulating strategic roadmaps for insightful analysis."
        - point: "Collaborating with fellow data analysts to construct paginated data reports using specialized tools like SQL Server Reporting Services (SSRS), ensuring comprehensive data representation and analysis."
    - company: "The Delivery Group"
      id: "TDG"
      role: "Data Processor (Bristol, England)"
      startdate: "May 2023"
      enddate: "-"
      featuredpoints:
        - point: "Perform in-depth data audits for gathered data with the goal of keeping the data up to high standards."
        - point: "Perform quality control checks on the database using a standardised process to determine the quality of the data by its accuracy, completeness, consistency, reliability, timeliness and relevance."
        - point: "Extensively use functions in Excel like VLOOKUP, HLOOKUP, INDEX, and MATCH for data lookup and retrieval tasks and highlight key trends and patterns using company software."
        - point: "Set up data validation rules to ensure data integrity and accuracy to ensure smooth execution of subsequent tasks in the data life cycle."
        - point: "Perform data cleansing tasks ensuring compliance by utilizing tools such as Power BI and Excel to provide insights and generate reports to highlight key influencers (KPIs) contributing towards effective decision-making processes."
        - point: "Utilizing SQL databases for data cleaning, manipulation, and processing, ensuring data accuracy and reliability in line with Royal Mail compliance and supply chains."
        - point: "Extensively use Excel Power Query to import, transform, and clean data from multiple sources, streamlining data preparation processes (ETL)."
        - point: "Implementing macros and writing VBA code to automate tasks in Excel, enhancing productivity and efficiency."
        - point: "Provide data quality services for accurate and compliant databases, ensuring data integrity and regulatory compliance by conducting audits."
        - point: "Resolve any ad-hoc data-related queries to ensure data integrity and usability."
      

  #certifications section
  disable_certification: false
  certification:  
     - Name: Preparing Data for Analysis with Microsoft Excel
       institution: Microsoft
       startdate: "September 2023"
       enddate: "October 2023"
       link:
         - weblink: "https://drive.google.com/file/d/1EtaH05rgSYkxA8psm7B8GuT37lBDoamI/view?usp=share_link"
           certificate: "View Certificate"
    
  # Education
  disable_education: false
  education:
    - degree: "MSc"
      branch: "Data Science"
      university: "University of Essex"
      startedyear: "2021"
      graduation: "2022"
    - degree: "B.E"
      branch: "Computer Science"
      university: "University of Mumbai"
      startedyear: "2016"
      graduation: "2020"
    - degree: "Diploma"
      branch: "Computer Science"
      university: "Maharashtra State Board of Technical Education (Mumbai)"
      startedyear: "2013"
      graduation: "2016"

  # Projects
  disable_projects: false
  projects:
  - name: "PowerBI Projects"
      img: /images/Microsoft-Power-BI-Symbol-300x270.png
      githublink: "https://github.com/ms21949/PowerBI-Projects"
      description: "This Power BI repository features projects on Superstore Sales Analysis and Twitch Streaming Analysis, providing comprehensive insights into sales performance and viewer engagement, respectively."
    - name: "Fake Review Detection Using Supervised Machine Learning"
      img: /images/nlp.png
      githublink: "https://github.com/ms21949/NLP"
      #featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "The idea behind this project was to use WordLemmatizer along with an N-gram Model. Further vectorising the Product-Review text using a Term Frequency - Inverse Document Frequency (TF-IDF) and then fine-tuning a supervised Machine Learning Model to predict if the review is fake or real."
    - name: "Coupon recommendation for vehicle infotainment systems"
      img: /images/vehicle.jpeg
      githublink: "https://github.com/ms21949/Binary-Classification"
      #featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "The following code is based on the dataset which was collected via a survey on Amazon Mechanical Turk. The survey describes different driving scenarios including the destination, current time, weather, passenger, etc., and then ask the person whether he will accept the coupon if he is the driver."
    - name: "Rossmann Store Sales Prediction"
      img: /images/sale.jpeg
      githublink: "https://github.com/ms21949/Sales-Prediction-"
      #featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "Rossmann operates over 3,000 drug stores in 7 European countries. Currently, Rossmann store managers are tasked with predicting their daily sales for up to six weeks in advance. Store sales are influenced by many factors, including promotions, competition, school and state holidays, seasonality, and locality. With thousands of individual managers predicting sales based on their unique circumstances, the accuracy of results can be quite varied."
    - name: "Construction Management Firm Evaluator (Deployed on AWS EC2)"
      img: /images/invest-real-estate-icon-flat-design-house-building-investment-money-industry-financial-finance-business-residential-61464178.jpeg
      githublink: "https://github.com/ms21949/Construction-Management-Firm-Evaluator"
      featuredlink: "http://ec2-34-228-37-227.compute-1.amazonaws.com:8080/"
      description: "After scraping and converting the data into a CSV, performed some Exploratory Data Analysis on the Dataset and implemented a Machine Learning Model to predict if the Firm is worth Investing and vice versa.  I have built an interactive Flask Web Application including two fields I. e, Rank and Revenue using the model developed in the previous step. "
    - name: "Credit Score Estimator"
      img: /images/creditscore.jpeg
      githublink: "https://github.com/ms21949/CreditScore-Estimator"
      featuredlink: "https://credit-score-estimator.herokuapp.com/"
      description: "Given a persons credit-related information, build a machine learning model that can classify the credit score."

    
    
    
    
  # services
  disable_achievements: true
  achievements:
    - title: "Website Development"
      description: "Design a website for personal use or for business purpose using HTML, CSS, JS and Python."
      img: /images/Website-Design-new.jpg
    - title: Data Analysis
      description: "With the help of tableu or python analyze the data of the business or client needs which help them to solve business problems."
      img: /images/da.jpg
      # url: https://example.com
    - title: Machine Learning & Deep Learning
      description: "Build various types of ML and DL models according to business or client needs in which it helps to solve complex business issues." 
      img: /images/ml.png
    
  # Contact
  disable_contact: false
  contact_content: My inbox is always open. Whether you have a question or just want to say hi, I'll try my best to get back to you! 
  email: "madhavsharma511@mail.com"

  # Footer
  socialiconfooter: true
  recentposts: true

  # Blog
  showdescription: false
  tweet: true
